### ISSUE TITLE
Document not found

### ISSUE THREAD

**Issue by Fwm0424** [ID56/Multimodal-Fusion-CRNN#3]
Hi, I tried to run train_DHG.py and eval_DHG.py, but there is an error that the files are not found.

OSError: ./data/informations_troncage_sequences.txt not found.

I can't find this file.I hope I can get some help with this.

**Comment by ID56** [comment]
Hi, this file is a part of the DHG dataset. Have you downloaded the DHG-14/28 dataset?

**Comment by Fwm0424** [comment]
Thank you very much! Regarding the last question it has been solved, but I was running eval_DHG.py while having added dhg.yaml and got an error. Is it because of missing parameters?
KeyError: "train"

**Comment by ID56** [comment]
Good catch, it seems to be a bug. The data loading and config were changed slightly, but the eval script seems to not have been updated. Will fix it later today, thank you!

**Comment by Fwm0424** [comment]
Hi, there seems to be no update on the content. I have written my own .yaml file and I'm not sure if it's written correctly so I wanted to borrow from the .yaml file you wrote. I'm a newbie and would appreciate your guidance.

**Comment by ID56** [comment]
Hello! Sorry I was extremely busy last couple of days. The fix is very simple, just the ["train"] key needed to be removed from [eval_DHG, line 92](https://github.com/ID56/Multimodal-Fusion-CRNN/blob/main/eval_DHG.py#L92).

I would also like to note that to run the evaluation, you also need trained model checkpoints. If you haven't trained your own model, I can help provide you with checkpoints (i.e. through Google drive, they should be around ~300MB).

**Comment by ID56** [comment]
I have added a [demo](https://github.com/ID56/Multimodal-Fusion-CRNN#tutorials), which shows how to set up training and evaluation on a Kaggle notebook.

I also have the DHG dataset stored in Kaggle, so if you want to train/eval your own model there, I could share the dataset with you privately; then you won't need to upload the ~5GB data yourself. (You can send me your kaggle username at my email, `mashrurmahmud [at] iut [dash] dhaka [dot] edu`).

**Comment by Fwm0424** [comment]
Hello, long time no see! I'm currently having a problem, I've learnt this project of yours and I've switched to another public dataset based on your code, which is RGB and depth image data. But when I train the new dataset, I keep reporting an error channel mismatch. RuntimeError: Given groups=1, weight of size [8, 1, 3, 3], expected input[512, 3, 50, 50] to have 1 channel, but got 3 channels instead when training separate depth images. I've spent a lot of time on this and never found the cause. I hope I can get your help.

**Comment by mashrurmorshed** [comment]
Hello! I need to know a bit more about your data.

On the SHREC/DHG datasets, the fusion models received this data:
- depth image sequence, of shape (batch, T, 1, 50, 50)
- skeleton coordinates, of shape (batch, T, 44)

You mentioned your data is RGB + Depth, so your data should probably be something like:
- rgb image sequence, of shape (batch, T, 3, 50, 50)
- depth image sequence, of shape (batch, T, 1, 50, 50)

--- 
From the error you mentioned, it seems like you are passing RGB images into the depth model. So the depth model expects 1 channel, but it's getting 3 channels.

Can you post two things:

- your dataset's `__getitem__()` method
- the shape of the data you pass into the model?

**Comment by Fwm0424** [comment]
Hello! My dear friend, I would like to share with you the good news that my last enquiry to you is solved! Thank you again for your patience in answering me!

**Comment by QienJane** [comment]
> Hi, this file is a part of the DHG dataset. Have you downloaded the DHG-14/28 dataset?
> 
> Here is a link to the [dataset page](http://www-rech.telecom-lille.fr/DHGdataset)
> 
> The files inside the dataset are like this:
> 
> ```
> +---gesture_1
> |   +---finger_1
> |  |   +---subject_1
> |  |  |   +---essai_1
> |  |  |   |   
> |  |  |   |   depth_1.png
> |  |  |   |   depth_2.png
> |  |  |   |   ...
> |  |  |   |   depth_N.png
> |  |  |   |   general_information.txt
> |  |  |   |   skeleton_image.txt
> |  |  |   |   skeleton_world.txt
> |  |  |   |
> |  |  |   \---essai_2
> |  |  |   ...
> |  |  |   \---essai_5
> |  |   \---subject_2
> |  |   ...
> |  |   \---subject_20
> |   \---finger_2
> ...
> \---gesture_14
> informations_troncage_sequences.txt
> ```

Hello, The DHG-14/28 dataset you provided is very similar to the contents of the SHREC 2017 dataset.

But the official website "http://www-rech.telecom-lille.fr/shrec2017-hand/" for downloading the SHREC17 dataset is no longer accessible.

Can you provide me with the following files from the SHREC17 dataset? If you can provide them, it would be a great help to my research.

The SHREC17 dataset include the overall folder that contains the folders "gesture_1" to "gesture_14".
This overall folder contains the following files:
+---gesture_1
| +---finger_1
| | +---subject_1
| | | +---essai_1
| | | | | |   
| | | | depth_0.png
| | | | depth_1.png
| | | | | | | | ...
| | | | depth_N-1.png
| | | | general_informations.txt
| | | skeletons_image.txt
| | | skeletons_world.txt
| | | | | |
| | | ---essai_2
| | | ...
| | ---essai_5
| ---subject_2
| ...
| ---subject_20
| ---finger_2
...
---gesture_14
